line_length:
    warning: 220
    error: 300
    ignores_function_declarations: true
    ignores_comments: true
    ignores_urls: true
function_body_length:
    warning: 300
    error: 500
nesting:
    type_level: 3
cyclomatic_complexity:
    ignores_case_statements: true
included:
- Bhavesh_Practical
excluded: # paths kto ignore during linting. Takes precedence over `included`.
- Carthage
- Pods
- Source/ExcludedFolder
- Source/ExcludedFile.swift
- Source/*/ExcludedFile.swift # Exclude files with a wildcard

